# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'LoginProcess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginProcess
  pod 'SwiftLint'
  pod 'SwiftFormat/CLI', '~> 0.49'

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'	
  pod 'JGProgressHUD'
  pod 'paper-onboarding'
  pod 'GoogleSignIn'

end
